// ===== articles.js — articles reading list =====

import { escapeHtml, safeUrl, showStatus, setSyncStatus } from './ui.js';
import { getFullApiUrl, fetchWithRetry } from './api.js';
import { showCyberLoader, hideCyberLoader } from './loader.js';
import { showAuthError } from './config.js';

const STATUS_CYCLE  = ['not-read', 'reading', 'read'];
const STATUS_LABELS = { 'not-read': 'Not Read', 'reading': 'Reading…', 'read': 'Read ✓' };

let articlesList      = [];
let hasArticleChanges = false;
let _config           = null;

export function initArticles(config) {
  _config = config;

  const addToggle      = document.getElementById('articlesAddToggle');
  const addForm        = document.getElementById('articleAddForm');
  const nameInput      = document.getElementById('articleNameInput');
  const linkInput      = document.getElementById('articleLinkInput');
  const cancelBtn      = document.getElementById('articleCancelBtn');
  const saveNewBtn     = document.getElementById('articleSaveBtn');
  const articlesSaveBtn = document.getElementById('articlesSaveBtn');

  addToggle?.addEventListener('click', () => {
    addForm?.classList.toggle('visible');
    if (addForm?.classList.contains('visible')) nameInput?.focus();
  });

  cancelBtn?.addEventListener('click', () => {
    addForm?.classList.remove('visible');
    if (nameInput) nameInput.value = '';
    if (linkInput) linkInput.value = '';
  });

  saveNewBtn?.addEventListener('click',  submitNewArticle);
  linkInput?.addEventListener('keydown', (e) => { if (e.key === 'Enter') submitNewArticle(); });
  nameInput?.addEventListener('keydown', (e) => { if (e.key === 'Enter') linkInput?.focus(); });

  articlesSaveBtn?.addEventListener('click', saveArticlesToHackMD);

  // Expose window functions for inline HTML generated by renderArticles
  window.cycleArticleStatus  = cycleArticleStatus;
  window.updateArticleProgress = updateArticleProgress;
  window.deleteArticle       = deleteArticle;

  window.addEventListener('beforeunload', (e) => {
    if (hasArticleChanges) { e.preventDefault(); e.returnValue = ''; }
  });
}

// ── Markdown serialisation ─────────────────────────────────────────

function articlesToMarkdown(articles) {
  const rows = articles.map(a =>
    `| ${a.id} | ${a.name.replace(/\|/g, '\\|')} | ${a.link} | ${a.status || 'not-read'} | ${a.progress ?? 0} |`
  ).join('\n');
  return `# Articles\n\n| id | name | link | status | progress |\n| -- | ---- | ---- | ------ | -------- |\n${rows}\n`;
}

function parseArticlesMarkdown(content) {
  const articles = [];
  const lines    = (content || '').split('\n');
  let inTable    = false;
  for (const line of lines) {
    if (!inTable) {
      if (line.startsWith('| id |') || line.startsWith('| id|')) inTable = true;
      continue;
    }
    if (/^\|[-| ]+\|/.test(line)) continue;
    if (!line.startsWith('|')) { inTable = false; continue; }
    const cells = line.split('|').slice(1, -1).map(c => c.trim());
    if (cells.length < 3) continue;
    const id = parseInt(cells[0], 10);
    if (isNaN(id)) continue;
    articles.push({
      id,
      name:     (cells[1] || '').replace(/\\\|/g, '|'),
      link:     cells[2] || '',
      status:   cells[3] || 'not-read',
      progress: parseInt(cells[4] || '0', 10) || 0,
    });
  }
  return articles;
}

// ── Render ─────────────────────────────────────────────────────────

export function renderArticles() {
  const statsEl     = document.getElementById('articlesStats');
  const containerEl = document.getElementById('articlesContainer');
  if (!statsEl || !containerEl) return;

  const total        = articlesList.length;
  const readCount    = articlesList.filter(a => a.status === 'read').length;
  const readingCount = articlesList.filter(a => a.status === 'reading').length;

  statsEl.innerHTML = `
    <div class="articles-stat"><span class="articles-stat-value">${total}</span><span class="articles-stat-label">Total</span></div>
    <div class="articles-stat stat-read"><span class="articles-stat-value">${readCount}</span><span class="articles-stat-label">Read</span></div>
    <div class="articles-stat stat-reading"><span class="articles-stat-value">${readingCount}</span><span class="articles-stat-label">Reading</span></div>
    <div class="articles-stat"><span class="articles-stat-value">${total - readCount - readingCount}</span><span class="articles-stat-label">Not Started</span></div>
  `;

  if (total === 0) {
    containerEl.innerHTML = `<div class="empty-state" style="padding:40px 0;"><p style="font-size:15px;color:var(--text-muted);">No articles yet — add one above.</p></div>`;
    return;
  }

  containerEl.innerHTML = articlesList.map((article, idx) => {
    const pct    = article.progress || 0;
    const isFull = pct === 100;
    let shortLink = article.link;
    try { shortLink = new URL(article.link).hostname.replace('www.', ''); } catch {}
    return `
      <div class="article-card" id="article-card-${article.id}">
        <div class="article-card-progress-bar">
          <div class="article-card-progress-fill ${isFull ? 'full' : ''}" style="width:${pct}%"></div>
        </div>
        <div class="article-card-body">
          <div class="article-num">${idx + 1}</div>
          <div class="article-card-main">
            <div class="article-title-row">
              <a class="article-title-link" href="${safeUrl(article.link)}" target="_blank" rel="noopener noreferrer">${escapeHtml(article.name)}</a>
              <span class="article-ext-icon">↗ ${escapeHtml(shortLink)}</span>
            </div>
            <div class="article-controls">
              <button class="article-status-btn ${article.status}" onclick="cycleArticleStatus(${article.id})">${STATUS_LABELS[article.status] || article.status}</button>
              <div class="article-progress-group">
                <input type="range" min="0" max="100" value="${pct}" class="article-progress-input"
                  oninput="updateArticleProgress(${article.id}, this.value)"
                  onchange="updateArticleProgress(${article.id}, this.value)">
                <span class="article-progress-pct" id="article-pct-${article.id}">${pct}%</span>
              </div>
            </div>
          </div>
          <button class="article-delete-btn" onclick="deleteArticle(${article.id})" title="Remove article">✕</button>
        </div>
      </div>
    `;
  }).join('');
}

// ── Actions ────────────────────────────────────────────────────────

function cycleArticleStatus(id) {
  const article = articlesList.find(a => a.id === id);
  if (!article) return;
  const currentIdx  = STATUS_CYCLE.indexOf(article.status);
  article.status    = STATUS_CYCLE[(currentIdx + 1) % STATUS_CYCLE.length];
  if (article.status === 'read') article.progress = 100;
  markArticleChanged();
  renderArticles();
}

function updateArticleProgress(id, value) {
  const article = articlesList.find(a => a.id === id);
  if (!article) return;
  const pct      = parseInt(value, 10);
  article.progress = pct;
  if (pct === 100)    article.status = 'read';
  else if (pct > 0)   article.status = 'reading';
  else                article.status = 'not-read';
  markArticleChanged();
  const fill      = document.querySelector(`#article-card-${id} .article-card-progress-fill`);
  const pctLabel  = document.getElementById(`article-pct-${id}`);
  const statusBtn = document.querySelector(`#article-card-${id} .article-status-btn`);
  if (fill)      { fill.style.width = pct + '%'; fill.className = 'article-card-progress-fill' + (pct === 100 ? ' full' : ''); }
  if (pctLabel)  pctLabel.textContent = pct + '%';
  if (statusBtn) { statusBtn.className = 'article-status-btn ' + article.status; statusBtn.textContent = STATUS_LABELS[article.status]; }
  const total       = articlesList.length;
  const readCount   = articlesList.filter(a => a.status === 'read').length;
  const readingCount = articlesList.filter(a => a.status === 'reading').length;
  const statsEl     = document.getElementById('articlesStats');
  if (statsEl) {
    const vals = statsEl.querySelectorAll('.articles-stat-value');
    if (vals[1]) vals[1].textContent = readCount;
    if (vals[2]) vals[2].textContent = readingCount;
    if (vals[3]) vals[3].textContent = total - readCount - readingCount;
  }
}

function deleteArticle(id) {
  articlesList = articlesList.filter(a => a.id !== id);
  markArticleChanged();
  renderArticles();
}

function markArticleChanged() {
  hasArticleChanges = true;
  const btn = document.getElementById('articlesSaveBtn');
  if (btn) btn.disabled = false;
}

function submitNewArticle() {
  const nameInput = document.getElementById('articleNameInput');
  const linkInput = document.getElementById('articleLinkInput');
  const addForm   = document.getElementById('articleAddForm');
  const name      = nameInput?.value.trim();
  const link      = linkInput?.value.trim();
  if (!name) { nameInput?.focus(); return; }
  if (!link) { linkInput?.focus(); return; }
  const newId = articlesList.length > 0 ? Math.max(...articlesList.map(a => a.id)) + 1 : 1;
  articlesList.push({ id: newId, name, link, status: 'not-read', progress: 0 });
  if (nameInput) nameInput.value = '';
  if (linkInput) linkInput.value = '';
  addForm?.classList.remove('visible');
  markArticleChanged();
  renderArticles();
  showStatus('Article added — save to HackMD to persist');
}

// ── HackMD ────────────────────────────────────────────────────────

export async function loadArticlesFromAPI(config) {
  _config = config;
  if (!config.API_TOKEN) { showStatus('Error: HackMD API Token is not configured'); return; }
  setSyncStatus('⟳ Loading…');
  try {
    const res = await fetch(getFullApiUrl(`/notes/${config.ARTICLES_NOTE_ID}`, config), {
      headers: { 'Authorization': 'Bearer ' + config.API_TOKEN }
    });
    if (!res.ok) {
      if (res.status === 401) { showAuthError(config); throw new Error('Unauthorized'); }
      throw new Error('Failed to load');
    }
    const data = await res.json();
    articlesList = parseArticlesMarkdown(data.content);
    if (articlesList.length === 0) {
      articlesList = [{ id: 1, name: 'Building an AI Assistant into a Web App — What I Learned and Where I Think This Is Going', link: 'https://medium.com/@dominicbachmann/building-an-ai-assistant-into-a-web-app-what-i-learned-and-where-i-think-this-is-going-8d8642a9623c', status: 'not-read', progress: 0 }];
      markArticleChanged();
    } else {
      hasArticleChanges = false;
      const btn = document.getElementById('articlesSaveBtn');
      if (btn) btn.disabled = true;
    }
    renderArticles();
    setSyncStatus('✓ Synced with HackMD', 'var(--accent)');
    setTimeout(() => setSyncStatus(''), 3000);
  } catch (e) {
    setSyncStatus('⚠ Articles load failed', '#e55');
    showStatus('Error loading articles: ' + e.message);
    renderArticles();
  }
}

async function saveArticlesToHackMD() {
  if (!hasArticleChanges) return;
  if (!_config.API_TOKEN)        { showStatus('Error: HackMD API Token is not configured'); return; }
  if (!_config.ARTICLES_NOTE_ID) { showStatus('Error: Articles Note ID is not configured — check Settings'); return; }
  const saveBtn = document.getElementById('articlesSaveBtn');
  if (saveBtn) { saveBtn.disabled = true; saveBtn.textContent = 'Saving…'; }
  setSyncStatus('⟳ Saving…');
  showCyberLoader('Uploading Articles');
  try {
    const res = await fetchWithRetry(getFullApiUrl(`/notes/${_config.ARTICLES_NOTE_ID}`, _config), {
      method:  'PATCH',
      headers: { 'Authorization': 'Bearer ' + _config.API_TOKEN, 'Content-Type': 'application/json' },
      body:    JSON.stringify({ content: articlesToMarkdown(articlesList) })
    });
    if (!res.ok) {
      if (res.status === 401) { showAuthError(_config); throw new Error('Unauthorized — check your API token'); }
      if (res.status === 403) throw new Error('Permission denied');
      if (res.status === 404) throw new Error('Articles note not found — check the Note ID in Settings');
      throw new Error(`Save failed (HTTP ${res.status})`);
    }
    hasArticleChanges = false;
    showStatus('Saved to HackMD ✓');
    setSyncStatus('✓ Saved', 'var(--accent)');
    setTimeout(() => setSyncStatus(''), 3000);
  } catch (e) {
    showStatus('Error saving: ' + e.message);
    setSyncStatus('⚠ Save failed', '#e55');
    if (saveBtn) saveBtn.disabled = false;
  }
  hideCyberLoader();
  if (saveBtn) saveBtn.textContent = 'Save to HackMD';
}
