functionsDirectory = "/Users/alig/Library/Application Support/Claude/local-agent-mode-sessions/3fdbc1c0-7b40-401d-b6c7-3e147deda3d7/a582e152-c67a-4ed4-a1f2-8cf92c1bda2e/local_43edcedc-58e8-4b04-a866-8a337422bc92/outputs/deploy_v2/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/alig/Library/Application Support/Claude/local-agent-mode-sessions/3fdbc1c0-7b40-401d-b6c7-3e147deda3d7/a582e152-c67a-4ed4-a1f2-8cf92c1bda2e/local_43edcedc-58e8-4b04-a866-8a337422bc92/outputs/deploy_v2"
publishOrigin = "config"
commandOrigin = "config"
command = "# no build needed"
functions = "/Users/alig/Library/Application Support/Claude/local-agent-mode-sessions/3fdbc1c0-7b40-401d-b6c7-3e147deda3d7/a582e152-c67a-4ed4-a1f2-8cf92c1bda2e/local_43edcedc-58e8-4b04-a866-8a337422bc92/outputs/deploy_v2/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]